### PR TITLE
Added MongoDB adapter.

### PR DESCRIPTION
**Pull request by YekitKsv**
Hello. 
We have a very big project, the main work with the cache, sessions and Ganesha takes place in MongoDB. Therefore, we cannot use Redis or Memcached. We implemented the MongoDB adapter and decided to share it with the public.
It may be necessary to add more tests.

---
Company: APISHIP LLC
Link: https://apiship.ru

### CODE REVIEW

**Comment by ackintosh** [comment]
@YekitKsv 
It's a Great job! Thanks for this PR and I'm pleased that Ganesha is being used in the project.

I've confirmed unit tests are passed locally. The failures in TravisCI will be fixed in another PR later. 😉

**Comment by ackintosh** [comment]
@YekitKsv Btw, may I add the company name (`APISHIP LLC`) as the company using Ganesha in the README? ✨

**Comment by ackintosh** [comment]
v0.3.0 has been released, which includes this enhancement. 🎉 

https://github.com/ackintosh/ganesha/releases/tag/0.3.0

**Comment by YekitKsv** [comment]
Of course. You can add the company in the readme.

**Comment by ackintosh** [comment]
Thanks, I've added the company. ✨ 

README > Companies using Ganesha 🚀
https://github.com/ackintosh/ganesha#companies-using-ganesha-rocket

**Pull request merged**
