### PR TITLE
Formatting changes

### PR DESCRIPTION
**Pull request by maxbaldanza**
* Remove docblocks that are no longer needed 
As we have types already added to the code
then the docblocks don't add anything
and actually make it harder to maintain

* Add CS formatting rules 
Make sure all classes are consistent
by having a new line after the opening tag.
At the minute there's a mixture of the two.
Removed unused imports

* Add phpunit cache to gitignore

### CODE REVIEW

**Comment by maxbaldanza** [comment]
@ackintosh any feedback?

**Comment by ackintosh** [comment]
Thank you for this PR, and I apologize for the delay! :pray: I will have a look at this by this weekend.

**Review by ackintosh — APPROVED** [review]
LGTM, thanks!

**Comment by ackintosh** [comment]
This PR has been released as v3.2 🎉 https://github.com/ackintosh/ganesha/releases/tag/3.2.0

**Pull request merged**
